name: Frontend Build

on:
  push:
    branches:
      - master

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          coverage: xdebug
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Copy .env
        working-directory: test-billetterie-app
        run: cp .env.example .env
      - name: Install Dependencies
        working-directory: test-billetterie-app
        run: composer update -q --no-ansi --no-interaction --no-scripts --no-progress --ignore-platform-reqs
      - name: Create Database
        working-directory: test-billetterie-app
        run: |
          mkdir -p database
          touch database/database.sqlite
      - name: Generate key
        working-directory: test-billetterie-app
        run: php artisan key:generate
      - name: Directory Permissions
        working-directory: test-billetterie-app
        run: chmod -R 777 storage bootstrap/cache
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install NPM dependencies
        working-directory: test-billetterie-app
        run: npm ci
      - name: Build Assets (Vite)
        working-directory: test-billetterie-app
        run: npm run build
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        working-directory: test-billetterie-app
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: |
          mkdir -p build/logs
          php artisan test --coverage-clover build/logs/clover.xml --log-junit build/logs/junit.xml
      - name: Execute end-to-end tests (Pest Browser)
        working-directory: test-billetterie-app
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: ./vendor/bin/pest tests/Browser
